### ISSUE TITLE
naming of APKs at releases

### ISSUE THREAD

**Issue by IzzySoft** [AdamGuidarini/MediTrak#127]
With v0.13.1 you've changed the naming scheme of APKs – which per se is not a big issue, but the way you changed them causes some issues on our end (with reproducible builds at IzzyOnDroid) as we no longer can fetch them as the name cannot be matched. We cannot use the Github API to list files, as you only use pre-releases, so we need to use "patterns" to evaluate the name.

Best explained by example:

```yaml
updates: tags:v[\d.]+
versions:
  - tag: v0.13.0
    apks:
      - apk_pattern: meditrak\.apk
        apk_url: https://github.com/AdamGuidarini/MediTrak/releases/download/$$TAG$$/meditrak.apk
```

This worked fine, as we could use the tag name to construct the APK URL. But with v0.13.1, the file name is `meditrak_0_13_1.apk` – and the `0_13_1` cannot be constructed with such a pattern as it has no matching part for the `0_13_1`.

That means, this version will fail RB now. And so will future ones using the same pattern.

Suggestions:

* you change it back to simply `meditrak.apk`
* you name it `meditrak_<tagName>.apk`, i.e. for tag v0.13.1 `meditrak_v0.13.1.apk` so we can use the tag name as pattern
* you use releases instead of pre-releases, and we can use the Github API :wink:

Can you help us there helping you? Thanks in advance!

cc @obfusk
